version: '3'

services:
  frontend:
    build: ./SkinCS
    restart: always
    ports:
      - 4200:80
    container_name: SkinCS-frontend

  backend:
    build: ./demo
    platform: linux/amd64
    restart: always
    ports: 
      - '8080:8080'
    container_name: SkinCS-backend
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
